server:
  port: 8082
spring:
  application:
    name: bildirim-service # name -> bildirim-service.yml dosyası anlamına geliyor
  cloud:
    config:
      profile: native
      uri: http://localhost:8888

  config:
    import: configserver:http://localhost:8888