#server: # -> yml dosyası boş kalmaması için geçici olarak tasindi
#  port: 8761

spring:
  application:
    name: eureka-server # eureka-server.yml
  cloud:
    config:
      profile: native
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888

eureka:
  server:
    renewal-percent-threshold: 0.5 # sağdaki hata icin # EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
    # https://stackoverflow.com/questions/39032741/what-does-renews-and-renews-threshold-mean-in-eureka

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true