server:
  port: 8761

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true