# http://localhost:8888/talimat-service.yml
spring:
  jpa:
    show-sql : true
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/mtusta?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true # allowPublicKeyRetrieval=true -> kaldırılacak
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    enabled: true # default
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
