server:
  port: 8081
spring:
  application:
    name: talimat-service # name -> talimat-service.yml dosyası anlamına geliyor
  cloud:
    config:
      profile: native
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888