# https://dzlab.github.io/monitoring/2021/12/30/monitoring-stack-docker/
version: '3.9'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    # volumes:                                        #################################
    #   - type: bind                                  #  BU SEKILDE YAZILABILIYORMUS  #
    #     source: ./prometheus.yml                    #                               #
    #     target: /etc/prometheus/prometheus.yml      #################################

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:9.0.5
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'

