# Resources
# https://webcache.googleusercontent.com/search?q=cache:4YxliYtBcBIJ:https://github.com/openzipkin-attic/docker-zipkin/blob/master/docker-compose.yml+&cd=1&hl=tr&ct=clnk&gl=tr
# https://github.com/openzipkin/zipkin/blob/master/docker/examples/
# https://github.com/openzipkin/zipkin/blob/master/docker/examples/docker-compose-cassandra.yml
version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin:${TAG:-latest}
    container_name: zipkin-server

    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

