version: '3.9'

services:
  ms-rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    container_name: 'rabbitmq'
    ports:
      # rabbitmq portu
      - 5672:5672
      # management arayuz portu
      - 15672:15672
      # rabbitmq prometheus portunu acmak icin yazilmasi lazim
      - 15692:15692
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
