server:
  port: 8888

# Hatası alınıyorsa;
# Dosya adı aşağıdaki şekilde değiştirilerek ve içerik olarak da bu şekilde kullanarak çalıştırılabilir.
#
# bootstrap.yml --> application.yml
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo # dizini belirt -> bu dizindeki configlerin hepsi load edilir
  profiles:
    active: native
  # bu ayarlari yazmasakta logging calisiyor SEBEBI:
  # pom eklendiğinden dolayı ve zipkin.enabled default olarak true olduğundan dolayı
  # hedef url de port u degistirmedigimizden, zipkin direk kayıt alıyor.
  zipkin:
    enabled: true # default
    base-url: http://localhost:9411/


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,beans